# Generated by Django 3.1.1 on 2020-10-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ablog', '0006_auto_20201002_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click Link Above To Read Blog Post....', max_length=255),
        ),
    ]
