# Generated by Django 3.1.1 on 2020-10-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ablog', '0007_post_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(max_length=255),
        ),
    ]
